AWSTemplateFormatVersion: 2010-09-09

Description: Creates Secrets for mdp stack

Parameters:
  Name:
    Type: String
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: Can contain only ASCII characters.
    Description: Name describing name of the resource
  Owner:
    Type: String
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: Can contain only ASCII characters.
    Description: Owner describing who is provisioning this resource
  Project:
    Type: String
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: Can contain only ASCII characters.
    Description: Project describing for which project this resource will be used
  Environment:
    Type: String
    Description: Environment declaration
  BusinessUnit:
    Description: Business Unit
    Type: String

Resources:
  PrefectAPISecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Store Prefect API Key in secret manager
      SecretString: "<Prefect API Key>"
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  GoogleOAuthSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Store Google oauth client id and secret
      SecretString: '{"ClientID":"<Client Id>","ClientSecret":"<Client Secret>"}'
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  AirbyteConnectionBuildSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Airbyte connection file secrets
      SecretString: '{}'
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  AirbyteDWSecondaryUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: DB password for Airbyte Data warehouse secondary user
      SecretString: '{"host":"<DB_HOST>","port":"<DB_PORT>","username":"<DB_USER>","password":"<DB_PASSWORD>","dbname":"<DB_NAME>"}'
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  SendGridAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: SendGrid API Key
      SecretString: '{"api_key": "<SendGrid API Key>"}'
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  HomeStorySFTPPrivateKeyForPennyMacSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Access to HomeStory SFTP with private key for PennyMac production user
      SecretString: '{"host":"<host>","username":"<username>","private_key":"<rsa private key>"}'
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  PostmarkTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Store Postmark API Token in secrets manager
      SecretString: "<Replace with Postmark API Token after cloud formation>"
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  PrefectAPISecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of Prefect API key
      Name: !Sub "${BusinessUnit}-${Environment}-prefect-api-secret-arn"
      Type: String
      Value: !Ref PrefectAPISecret
      Tags:
        Name: !Ref Name
        Owner: !Ref Owner
        Project: !Ref Project
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit

  GoogleOAuthSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of Google OAuth secret
      Name: !Sub "${BusinessUnit}-${Environment}-google-oauth-secret-arn"
      Type: String
      Value: !Ref GoogleOAuthSecret
      Tags:
        Name: !Ref Name
        Owner: !Ref Owner
        Project: !Ref Project
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit

  AirbyteConnectionBuildSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of Airbyte connection build secret 
      Name: !Sub "${BusinessUnit}-${Environment}-airbyte-connection-build-secret-arn"
      Type: String
      Value: !Ref AirbyteConnectionBuildSecret
      Tags:
        Name: !Ref Name
        Owner: !Ref Owner
        Project: !Ref Project
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit

  AirbyteDWSecondaryUserSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of Airbyte Data warehouse secondary user secret
      Name: !Sub "${BusinessUnit}-${Environment}-airbyte-dw-secondary-user-secret-arn"
      Type: String
      Value: !Ref AirbyteDWSecondaryUserSecret
      Tags:
        Name: !Ref Name
        Owner: !Ref Owner
        Project: !Ref Project
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit

  SendGridAPIKeySecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of SendGrid API Key
      Name: !Sub "${BusinessUnit}-${Environment}-sendgrid-api-key-secret-arn"
      Type: String
      Value: !Ref SendGridAPIKeySecret
      Tags:
        Name: !Ref Name
        Owner: !Ref Owner
        Project: !Ref Project
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit

  HomeStorySFTPPrivateKeyForPennyMacSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of HomeStory SFTP private key for PennyMac production user
      Name: !Sub "${BusinessUnit}-${Environment}-homestory-sftp-private-key-for-penny-mac-secret-arn"
      Type: String
      Value: !Ref HomeStorySFTPPrivateKeyForPennyMacSecret
      Tags:
        Name: !Ref Name
        Owner: !Ref Owner
        Project: !Ref Project
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit

  PostmarkTokenSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of Postmark API Token
      Name: !Sub "${BusinessUnit}-${Environment}-postmark-token-secret-arn"
      Type: String
      Value: !Ref PostmarkTokenSecret
      Tags:
        Name: !Ref Name
        Owner: !Ref Owner
        Project: !Ref Project
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
