ENV_WEBHOOKS_QUEUE_NAME = 'WEBHOOKS_QUEUE_NAME'
ENV_S3_BUCKET_NAME = 'S3_BUCKET_NAME'
ENV_QUEUE_MAX_BATCH_SIZE = 'QUEUE_MAX_BATCH_SIZE'
ENV_QUEUE_MAX_WAIT_TIME = 'QUEUE_MAX_WAIT_TIME'
ENV_MESSAGES_POLLING_LIMIT = 'MESSAGES_POLLING_LIMIT'

DELETE_BATCH_SIZE_DEFAULT = 10

MESSAGES_POLLING_LIMIT_DEFAULT = 6000

S3_FILE_PATH_FORMAT = 'postmark/webhooks/$RECORD_TYPE/$DATE/$TIMESTAMP.csv'
