INSERT = 'INSERT'
MODIFY = 'MODIFY'

RECORDS = 'Records'
EVENT_NAME = 'eventName'
NEW_IMAGE = 'NewImage'
DYNAMO_DB = 'dynamodb'

DAG_NAME = 'dag_name'
TEMPLATE_FILE = 'template_file'

CONFIG_PARAMS_MAP_PLACEHOLDER = '{{CONFIG_PARAMS_MAP_PLACEHOLDER}}'

TMP_PATH = '/tmp'
DAG_TEMPLATE_BASE_DIR = 'dags_template'
DAGS_S3_PATH = 'airflow/dags/'

DAG_NAME_KEY_ENV = 'DAG_NAME_KEY'
TEMPLATE_FILE_KEY_ENV = 'TEMPLATE_FILE_KEY'
S3_BUCKET_KEY_ENV = 'S3_BUCKET_NAME'
DAGS_S3_PATH_KEY_ENV = 'DAGS_S3_PATH_KEY'
