BITLY_API_DOMAIN = 'https://api-ssl.bitly.com/v4'
ENV_PARTNER = 'PARTNER'
ENV_PARTNER_SMS_KEY = 'PARTNER_SMS_KEY'
ENV_BUCKET_NAME = 'BUCKET_NAME'
ENV_BITLY_GROUP = 'BITLY_GROUP'
S3_KEY = 'S3_KEY'

SECRET_STRING = 'SecretString'
SECRET_BINARY = 'SecretBinary'
