AWSTemplateFormatVersion: 2010-09-09

Description: CI/CD pipeline setup for airbyte updates

Parameters:
  Name:
    Type: String
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: Can contain only ASCII characters.
    Description: Name describing name of the resource
  Owner:
    Type: String
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: Can contain only ASCII characters.
    Description: Owner describing who is provisioning this resource
  Project:
    Type: String
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: Can contain only ASCII characters.
    Description: Project describing for which project this resource will be used
  Environment:
    Type: String
    Description: Environment declaration
  BusinessUnit:
    Description: Business Unit
    Type: String
  CodeStarConnectionId:
    Type: String
    Description: bitbucket codestar connection id
  FullRepositoryName:
    Type: String
    Description: Full name of repository which act as source for codepipeline
  SourceBranchName:
    Type: String
    Description: name of the branch which act as source
  VpcId:
    Description: VPC to use
    Type: AWS::EC2::VPC::Id
  CodeBuildSubnets:
    Description: The Subnets which Codebuild use
    Type: List<AWS::EC2::Subnet::Id>
  AirbyteStackName:
    Type: String
    Description: Name of Airbyte cloudformation stack
  AirflowStackName:
    Type: String
    Description: Name of Airflow cloudformation stack
  EC2Username:
    Type: String
    Description: username to of ec2 instance
  S3ArtifactBucket:
    Type: String
    Description: S3 bucket name where to store codepipeline artifact
  AirbyteCodebuildEC2Key:
    Type: AWS::SSM::Parameter::Name
    Description: Name of the parameter which holds the ssh key that has access to airbyte server
  MDPNotificationsStackName:
    Type: String
    Description: Name of mdp notifications cloudformation stack

Resources:
  CodepipelineStatusNotificationRule:
    Type: 'AWS::CodeStarNotifications::NotificationRule'
    Properties:
      Name: !Sub "${Name}-${Environment}-manual-approval-rule"
      DetailType: FULL
      Resource: !Sub
        - arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}
        - PipelineName: !Ref CodePipeline
      EventTypeIds:
        - codepipeline-pipeline-pipeline-execution-failed
        - codepipeline-pipeline-pipeline-execution-canceled
        - codepipeline-pipeline-pipeline-execution-started
      Targets:
        - TargetType: SNS
          TargetAddress:
            Fn::ImportValue: !Sub '${MDPNotificationsStackName}--MDPCodepipelineApprovalTopicArn'
      Tags:
        Name: !Ref Name
        Owner: !Ref Owner
        Project: !Ref Project
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit

  CodepipelineFailureNotificationRule:
    Type: 'AWS::CodeStarNotifications::NotificationRule'
    Description: Notification Rule to trigger codepipeline failure notifications to SNS
    Properties:
      Name: !Sub "${Name}-${Environment}-pipeline-failure-rule"
      DetailType: FULL
      Resource: !Sub
        - arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}
        - PipelineName: !Ref CodePipeline
      EventTypeIds:
        - codepipeline-pipeline-pipeline-execution-failed
      Targets:
        - TargetType: SNS
          TargetAddress:
            Fn::ImportValue: !Sub '${MDPNotificationsStackName}-DatapipelineErrorsTopicArn'
      Tags:
        Name: !Ref Name
        Owner: !Ref Owner
        Project: !Ref Project
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Sid: ''
        Version: '2012-10-17'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSCodeStarServiceRole
        - arn:aws:iam::aws:policy/AWSCodeStarFullAccess
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - codestar-connections:UseConnection
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/${CodeStarConnectionId}'
              - Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Effect: Allow
                Resource: '*'
              - Action:
                  - s3:*
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:s3:::${S3ArtifactBucket}'
            Version: '2012-10-17'
          PolicyName: codepipelinepolicy
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  CodeBuildSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Description: Policies required by codebuild to access Airbyte instance
    Properties:
      GroupName: !Sub "${Name}-${Environment}-codebuild-security-group"
      GroupDescription: Group for airbyte-pipeline codebuild security permission
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  AirbyteUpgradeTestBuild:
    Type: AWS::CodeBuild::Project
    Description: Codebuild to test the connector versions on new airbyte version
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:6.0'
        Type: LINUX_CONTAINER
        PrivilegedMode: True
      ServiceRole: !GetAtt CodeBuildRole.Arn
      TimeoutInMinutes: 60
      VpcConfig:
        SecurityGroupIds:
          - !Ref CodeBuildSecurityGroup
        Subnets: !Ref CodeBuildSubnets
        VpcId: !Ref VpcId
      Source:
        Type: CODEPIPELINE
        BuildSpec: "build_specs/test-buildspec.yml"
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  AirbyteUpgradeDeployBuild:
    Type: AWS::CodeBuild::Project
    Description: Codebuild for updating airbyte to new version and restoring connectors to required version
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:6.0'
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: SSH_KEY
            Type: PARAMETER_STORE
            Value: !Sub '${AirbyteCodebuildEC2Key}'
          - Name: AIRBYTE_STACK_NAME
            Type: PLAINTEXT
            Value: !Ref AirbyteStackName
          - Name: HOST
            Type: PLAINTEXT
            Value:
              Fn::ImportValue: !Sub '${AirbyteStackName}-EC2PrivateIp'
          - Name: PORT
            Type: PLAINTEXT
            Value: "80"
          - Name: EC2_USERNAME
            Type: PLAINTEXT
            Value: !Ref EC2Username
          - Name: AIRBYTE_LOG_GROUP_NAME
            Type: PLAINTEXT
            Value:
              Fn::ImportValue: !Sub '${AirbyteStackName}-AirbyteLogGroupName'
        PrivilegedMode: True
      ServiceRole: !GetAtt CodeBuildRole.Arn
      TimeoutInMinutes: 60
      VpcConfig:
        SecurityGroupIds:
          - !Ref CodeBuildSecurityGroup
        Subnets: !Ref CodeBuildSubnets
        VpcId: !Ref VpcId
      Source:
        Type: CODEPIPELINE
        BuildSpec: "build_specs/deploy-buildspec.yml"
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit

  EC2SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allows airbyte EC2 instance access from codebuild server
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !Ref CodeBuildSecurityGroup
      GroupId:
        Fn::ImportValue: !Sub '${AirbyteStackName}-EC2SecurityGroupId'

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Description: Main pipeline for airbyte deployment
    Properties:
      Name: !Sub '${Name}-${Environment}-pipeline'
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Location: !Ref S3ArtifactBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: GetSourceCodeRepository
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Sub 'arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/${CodeStarConnectionId}'
                BranchName: !Ref SourceBranchName
                FullRepositoryId: !Ref FullRepositoryName
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              OutputArtifacts:
                - Name: SourceCodeRepository
              Namespace: SourceVariables
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: TestAirbyteVersion
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref AirbyteUpgradeTestBuild
              RunOrder: 1
              InputArtifacts:
                - Name: SourceCodeRepository
        - Name: Approval
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              RunOrder: 1
              Configuration:
                NotificationArn:
                  Fn::ImportValue: !Sub '${MDPNotificationsStackName}--MDPCodepipelineApprovalTopicArn'
                CustomData: >
                  Test for connector pinning on Airbyte new version is done
        - Name: Deploy
          Actions:
            - Name: DeployAirbyteVersion
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref AirbyteUpgradeDeployBuild
              RunOrder: 1
              InputArtifacts:
                - Name: SourceCodeRepository
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
