version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "Applying ${MDP_SECRETS_STACK_NAME} change set"
      - python scripts/utils/stack_deploy.py --region $REGION --change-set-name ${MDP_SECRETS_CHANGE_SET_NAME} --stack-name ${MDP_SECRETS_STACK_NAME} --only-execute-changeset
      - echo "CHANGESET APPLY COMPLETED"
